service: the-bookclub-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  stocks-api:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: stocks
          method: get