service: the-bookclub-op-api

frameworkVersion: '2'

provider:
  name: aws
  profile: serverless-profile
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  searchBooks:
    handler: com.readers.thebookclub.Handler
    description: pass param to search books (not in stock)
    events:
      - http:
          path: /search/books/{param}
          method: GET
          cors:
            origin: '*'
  testStock:
    handler: com.readers.thebookclub.Handler
    description: test function to return a single stock
    events:
      - http:
          path: /test/stock/{param}
          method: GET
          cors:
            origin: '*'
  testInput:
    handler: com.readers.thebookclub.Handler
    description: test function to validate input
    events:
      - http:
          path: /test/input/{param}
          method: GET
          cors:
            origin: '*'
