service: the-bookclub-api

frameworkVersion: '2'

provider:
  name: aws
  profile: serverless
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  getStocks:
    handler: com.readers.thebookclub.Handler
    description: pass param as json to get stock from database
    events:
      - httpApi:
          path: /get/stocks/{param}
          method: GET
  setStocks:
    handler: com.readers.thebookclub.Handler
    description: pass param as json to set stock to database
    events:
      - httpApi:
          path: /set/stocks/{param}
          method: POST
  searchBooks:
    handler: com.readers.thebookclub.Handler
    description: pass param to search books (not in stock)
    events:
      - httpApi:
          path: /search/books/{param}
          method: GET
  testStock:
    handler: com.readers.thebookclub.Handler
    description: test function to return a single stock
    events:
      - httpApi:
          path: /test/stock/{param}
          method: GET
  testInput:
    handler: com.readers.thebookclub.Handler
    description: test function to validate input
    events:
      - httpApi:
          path: /test/input/{param}
          method: GET
