service: the-bookclub-api

frameworkVersion: '2'

provider:
  name: aws
  profile: serverless-profile
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  getDonateStock:
    handler: com.readers.thebookclub.handlers.GetDonateStockHandler
    description: get initial book list available to donate
    events:
      - http:
          path: /donate/stocks/
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getRequestStock:
    handler: com.readers.thebookclub.handlers.GetRequestStockHandler
    description: get initial book list available to request
    events:
      - http:
          path: /request/stocks/
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getActiveRegions:
    handler: com.readers.thebookclub.handlers.GetActiveRegionsHandler
    description: get activate regions
    events:
      - http:
          path: /regions/active/
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getRegionDetail:
    handler: com.readers.thebookclub.handlers.GetRegionDetailHandler
    description: get region details
    events:
      - http:
          path: /regions/{regionId}/details/
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  
    
