service: the-bookclub-api

frameworkVersion: '2'

provider:
  name: aws
  profile: serverless
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  stocks:
    handler: com.readers.thebookclub.Handler
    events:
      - httpApi:
          path: /get/stocks/{param}
          method: GET