service: the-bookclub-api

frameworkVersion: '2'

provider:
  name: aws
  profile: serverless-profile
  runtime: java8
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
 
package:
  artifact: target/the-bookclub-api-v0.1.jar

functions:
  getDonateStock:
    handler: com.readers.thebookclub.handlers.GetDonateStockHandler
    description: get initial book list available to donate
    events:
      - http:
          path: /donate/stocks/
          method: GET

  getRequestStock:
    handler: com.readers.thebookclub.handlers.GetRequestStockHandler
    description: get initial book list available to reques
    events:
      - http:
          path: /request/stocks/
          method: GET
  
    
