# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test getStock

on:
  push:
    branches: [ main, test-junit ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: testSetup
      run: mvn test -Dtest=TestApi#testSetup
#     - name: serchBook
#       run: mvn test -Dtest=TestApi#searchBook
    - name: checkStocksByIsbn
      run: mvn test -Dtest=TestApi#checkStocksByIsbn
#     - name: searchBookByIsbn
#       run: mvn test -Dtest=TestApi#searchBookByIsbn
